/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as GuestRouteRouteImport } from "./routes/_guest/route"
import { Route as AuthedRouteRouteImport } from "./routes/_authed/route"
import { Route as AuthedIndexRouteImport } from "./routes/_authed/index"
import { Route as GuestLoginRouteImport } from "./routes/_guest/login"
import { Route as AuthedSavedRouteImport } from "./routes/_authed/saved"

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: "/_guest",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthedSavedRoute = AuthedSavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthedIndexRoute
  "/saved": typeof AuthedSavedRoute
  "/login": typeof GuestLoginRoute
}
export interface FileRoutesByTo {
  "/": typeof AuthedIndexRoute
  "/saved": typeof AuthedSavedRoute
  "/login": typeof GuestLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authed": typeof AuthedRouteRouteWithChildren
  "/_guest": typeof GuestRouteRouteWithChildren
  "/_authed/saved": typeof AuthedSavedRoute
  "/_guest/login": typeof GuestLoginRoute
  "/_authed/": typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/saved" | "/login"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/saved" | "/login"
  id:
    | "__root__"
    | "/_authed"
    | "/_guest"
    | "/_authed/saved"
    | "/_guest/login"
    | "/_authed/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_guest": {
      id: "/_guest"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/": {
      id: "/_authed/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    "/_guest/login": {
      id: "/_guest/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    "/_authed/saved": {
      id: "/_authed/saved"
      path: "/saved"
      fullPath: "/saved"
      preLoaderRoute: typeof AuthedSavedRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedSavedRoute: typeof AuthedSavedRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedSavedRoute: AuthedSavedRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
