/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as GuestRouteRouteImport } from "./routes/_guest/route"
import { Route as AuthedRouteRouteImport } from "./routes/_authed/route"
import { Route as GuestLoginRouteImport } from "./routes/_guest/login"
import { Route as AuthedSavedRouteImport } from "./routes/_authed/saved"
import { Route as AuthedPlannerRouteImport } from "./routes/_authed/planner"
import { Route as AuthedExploreRouteRouteImport } from "./routes/_authed/_explore/route"
import { Route as AuthedExploreIndexRouteImport } from "./routes/_authed/_explore/index"
import { Route as AuthedPlannerPlaceGooglePlaceIdRouteImport } from "./routes/_authed/planner.place.$googlePlaceId"
import { Route as AuthedExploreAttractionAttractionIdRouteImport } from "./routes/_authed/_explore/attraction.$attractionId"
import { Route as AuthedPlannerPlaceGooglePlaceIdModalRouteImport } from "./routes/_authed/planner.place.$googlePlaceId_.modal"

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: "/_guest",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthedSavedRoute = AuthedSavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPlannerRoute = AuthedPlannerRouteImport.update({
  id: "/planner",
  path: "/planner",
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedExploreRouteRoute = AuthedExploreRouteRouteImport.update({
  id: "/_explore",
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedExploreIndexRoute = AuthedExploreIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedExploreRouteRoute,
} as any)
const AuthedPlannerPlaceGooglePlaceIdRoute =
  AuthedPlannerPlaceGooglePlaceIdRouteImport.update({
    id: "/place/$googlePlaceId",
    path: "/place/$googlePlaceId",
    getParentRoute: () => AuthedPlannerRoute,
  } as any)
const AuthedExploreAttractionAttractionIdRoute =
  AuthedExploreAttractionAttractionIdRouteImport.update({
    id: "/attraction/$attractionId",
    path: "/attraction/$attractionId",
    getParentRoute: () => AuthedExploreRouteRoute,
  } as any)
const AuthedPlannerPlaceGooglePlaceIdModalRoute =
  AuthedPlannerPlaceGooglePlaceIdModalRouteImport.update({
    id: "/place/$googlePlaceId_/modal",
    path: "/place/$googlePlaceId/modal",
    getParentRoute: () => AuthedPlannerRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthedExploreIndexRoute
  "/planner": typeof AuthedPlannerRouteWithChildren
  "/saved": typeof AuthedSavedRoute
  "/login": typeof GuestLoginRoute
  "/attraction/$attractionId": typeof AuthedExploreAttractionAttractionIdRoute
  "/planner/place/$googlePlaceId": typeof AuthedPlannerPlaceGooglePlaceIdRoute
  "/planner/place/$googlePlaceId/modal": typeof AuthedPlannerPlaceGooglePlaceIdModalRoute
}
export interface FileRoutesByTo {
  "/": typeof AuthedExploreIndexRoute
  "/planner": typeof AuthedPlannerRouteWithChildren
  "/saved": typeof AuthedSavedRoute
  "/login": typeof GuestLoginRoute
  "/attraction/$attractionId": typeof AuthedExploreAttractionAttractionIdRoute
  "/planner/place/$googlePlaceId": typeof AuthedPlannerPlaceGooglePlaceIdRoute
  "/planner/place/$googlePlaceId/modal": typeof AuthedPlannerPlaceGooglePlaceIdModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authed": typeof AuthedRouteRouteWithChildren
  "/_guest": typeof GuestRouteRouteWithChildren
  "/_authed/_explore": typeof AuthedExploreRouteRouteWithChildren
  "/_authed/planner": typeof AuthedPlannerRouteWithChildren
  "/_authed/saved": typeof AuthedSavedRoute
  "/_guest/login": typeof GuestLoginRoute
  "/_authed/_explore/": typeof AuthedExploreIndexRoute
  "/_authed/_explore/attraction/$attractionId": typeof AuthedExploreAttractionAttractionIdRoute
  "/_authed/planner/place/$googlePlaceId": typeof AuthedPlannerPlaceGooglePlaceIdRoute
  "/_authed/planner/place/$googlePlaceId_/modal": typeof AuthedPlannerPlaceGooglePlaceIdModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/planner"
    | "/saved"
    | "/login"
    | "/attraction/$attractionId"
    | "/planner/place/$googlePlaceId"
    | "/planner/place/$googlePlaceId/modal"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/planner"
    | "/saved"
    | "/login"
    | "/attraction/$attractionId"
    | "/planner/place/$googlePlaceId"
    | "/planner/place/$googlePlaceId/modal"
  id:
    | "__root__"
    | "/_authed"
    | "/_guest"
    | "/_authed/_explore"
    | "/_authed/planner"
    | "/_authed/saved"
    | "/_guest/login"
    | "/_authed/_explore/"
    | "/_authed/_explore/attraction/$attractionId"
    | "/_authed/planner/place/$googlePlaceId"
    | "/_authed/planner/place/$googlePlaceId_/modal"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_guest": {
      id: "/_guest"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_guest/login": {
      id: "/_guest/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    "/_authed/saved": {
      id: "/_authed/saved"
      path: "/saved"
      fullPath: "/saved"
      preLoaderRoute: typeof AuthedSavedRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    "/_authed/planner": {
      id: "/_authed/planner"
      path: "/planner"
      fullPath: "/planner"
      preLoaderRoute: typeof AuthedPlannerRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    "/_authed/_explore": {
      id: "/_authed/_explore"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedExploreRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    "/_authed/_explore/": {
      id: "/_authed/_explore/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthedExploreIndexRouteImport
      parentRoute: typeof AuthedExploreRouteRoute
    }
    "/_authed/planner/place/$googlePlaceId": {
      id: "/_authed/planner/place/$googlePlaceId"
      path: "/place/$googlePlaceId"
      fullPath: "/planner/place/$googlePlaceId"
      preLoaderRoute: typeof AuthedPlannerPlaceGooglePlaceIdRouteImport
      parentRoute: typeof AuthedPlannerRoute
    }
    "/_authed/_explore/attraction/$attractionId": {
      id: "/_authed/_explore/attraction/$attractionId"
      path: "/attraction/$attractionId"
      fullPath: "/attraction/$attractionId"
      preLoaderRoute: typeof AuthedExploreAttractionAttractionIdRouteImport
      parentRoute: typeof AuthedExploreRouteRoute
    }
    "/_authed/planner/place/$googlePlaceId_/modal": {
      id: "/_authed/planner/place/$googlePlaceId_/modal"
      path: "/place/$googlePlaceId/modal"
      fullPath: "/planner/place/$googlePlaceId/modal"
      preLoaderRoute: typeof AuthedPlannerPlaceGooglePlaceIdModalRouteImport
      parentRoute: typeof AuthedPlannerRoute
    }
  }
}

interface AuthedExploreRouteRouteChildren {
  AuthedExploreIndexRoute: typeof AuthedExploreIndexRoute
  AuthedExploreAttractionAttractionIdRoute: typeof AuthedExploreAttractionAttractionIdRoute
}

const AuthedExploreRouteRouteChildren: AuthedExploreRouteRouteChildren = {
  AuthedExploreIndexRoute: AuthedExploreIndexRoute,
  AuthedExploreAttractionAttractionIdRoute:
    AuthedExploreAttractionAttractionIdRoute,
}

const AuthedExploreRouteRouteWithChildren =
  AuthedExploreRouteRoute._addFileChildren(AuthedExploreRouteRouteChildren)

interface AuthedPlannerRouteChildren {
  AuthedPlannerPlaceGooglePlaceIdRoute: typeof AuthedPlannerPlaceGooglePlaceIdRoute
  AuthedPlannerPlaceGooglePlaceIdModalRoute: typeof AuthedPlannerPlaceGooglePlaceIdModalRoute
}

const AuthedPlannerRouteChildren: AuthedPlannerRouteChildren = {
  AuthedPlannerPlaceGooglePlaceIdRoute: AuthedPlannerPlaceGooglePlaceIdRoute,
  AuthedPlannerPlaceGooglePlaceIdModalRoute:
    AuthedPlannerPlaceGooglePlaceIdModalRoute,
}

const AuthedPlannerRouteWithChildren = AuthedPlannerRoute._addFileChildren(
  AuthedPlannerRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedExploreRouteRoute: typeof AuthedExploreRouteRouteWithChildren
  AuthedPlannerRoute: typeof AuthedPlannerRouteWithChildren
  AuthedSavedRoute: typeof AuthedSavedRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedExploreRouteRoute: AuthedExploreRouteRouteWithChildren,
  AuthedPlannerRoute: AuthedPlannerRouteWithChildren,
  AuthedSavedRoute: AuthedSavedRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
