/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as GuestRouteRouteImport } from "./routes/_guest/route"
import { Route as AuthedRouteRouteImport } from "./routes/_authed/route"
import { Route as GuestLoginRouteImport } from "./routes/_guest/login"
import { Route as AuthedSavedRouteImport } from "./routes/_authed/saved"
import { Route as AuthedExploreRouteRouteImport } from "./routes/_authed/_explore/route"
import { Route as AuthedExploreIndexRouteImport } from "./routes/_authed/_explore/index"
import { Route as AuthedExploreAttractionAttractionIdRouteImport } from "./routes/_authed/_explore/attraction.$attractionId"

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: "/_guest",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthedSavedRoute = AuthedSavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedExploreRouteRoute = AuthedExploreRouteRouteImport.update({
  id: "/_explore",
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedExploreIndexRoute = AuthedExploreIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedExploreRouteRoute,
} as any)
const AuthedExploreAttractionAttractionIdRoute =
  AuthedExploreAttractionAttractionIdRouteImport.update({
    id: "/attraction/$attractionId",
    path: "/attraction/$attractionId",
    getParentRoute: () => AuthedExploreRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthedExploreIndexRoute
  "/saved": typeof AuthedSavedRoute
  "/login": typeof GuestLoginRoute
  "/attraction/$attractionId": typeof AuthedExploreAttractionAttractionIdRoute
}
export interface FileRoutesByTo {
  "/": typeof AuthedExploreIndexRoute
  "/saved": typeof AuthedSavedRoute
  "/login": typeof GuestLoginRoute
  "/attraction/$attractionId": typeof AuthedExploreAttractionAttractionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authed": typeof AuthedRouteRouteWithChildren
  "/_guest": typeof GuestRouteRouteWithChildren
  "/_authed/_explore": typeof AuthedExploreRouteRouteWithChildren
  "/_authed/saved": typeof AuthedSavedRoute
  "/_guest/login": typeof GuestLoginRoute
  "/_authed/_explore/": typeof AuthedExploreIndexRoute
  "/_authed/_explore/attraction/$attractionId": typeof AuthedExploreAttractionAttractionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/saved" | "/login" | "/attraction/$attractionId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/saved" | "/login" | "/attraction/$attractionId"
  id:
    | "__root__"
    | "/_authed"
    | "/_guest"
    | "/_authed/_explore"
    | "/_authed/saved"
    | "/_guest/login"
    | "/_authed/_explore/"
    | "/_authed/_explore/attraction/$attractionId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_guest": {
      id: "/_guest"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_guest/login": {
      id: "/_guest/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    "/_authed/saved": {
      id: "/_authed/saved"
      path: "/saved"
      fullPath: "/saved"
      preLoaderRoute: typeof AuthedSavedRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    "/_authed/_explore": {
      id: "/_authed/_explore"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedExploreRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    "/_authed/_explore/": {
      id: "/_authed/_explore/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthedExploreIndexRouteImport
      parentRoute: typeof AuthedExploreRouteRoute
    }
    "/_authed/_explore/attraction/$attractionId": {
      id: "/_authed/_explore/attraction/$attractionId"
      path: "/attraction/$attractionId"
      fullPath: "/attraction/$attractionId"
      preLoaderRoute: typeof AuthedExploreAttractionAttractionIdRouteImport
      parentRoute: typeof AuthedExploreRouteRoute
    }
  }
}

interface AuthedExploreRouteRouteChildren {
  AuthedExploreIndexRoute: typeof AuthedExploreIndexRoute
  AuthedExploreAttractionAttractionIdRoute: typeof AuthedExploreAttractionAttractionIdRoute
}

const AuthedExploreRouteRouteChildren: AuthedExploreRouteRouteChildren = {
  AuthedExploreIndexRoute: AuthedExploreIndexRoute,
  AuthedExploreAttractionAttractionIdRoute:
    AuthedExploreAttractionAttractionIdRoute,
}

const AuthedExploreRouteRouteWithChildren =
  AuthedExploreRouteRoute._addFileChildren(AuthedExploreRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedExploreRouteRoute: typeof AuthedExploreRouteRouteWithChildren
  AuthedSavedRoute: typeof AuthedSavedRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedExploreRouteRoute: AuthedExploreRouteRouteWithChildren,
  AuthedSavedRoute: AuthedSavedRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
